-- URL shortener schema (V1). Hibernate runs in validate mode against this.

CREATE TABLE url_mappings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code  VARCHAR(16)  NOT NULL,
    long_url    VARCHAR(2048) NOT NULL,
    created_by  VARCHAR(255),
    click_count BIGINT       NOT NULL DEFAULT 0,
    expires_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL
);

-- Unique index on short_code: enforces no duplicate codes/aliases AND makes the
-- redirect lookup (the hot read path) an index seek.
CREATE UNIQUE INDEX idx_url_short_code ON url_mappings (short_code);

-- Supports keyset pagination of a user's URLs (WHERE created_by = ? AND id < ? ORDER BY id DESC).
CREATE INDEX idx_url_created_by_id ON url_mappings (created_by, id DESC);
